Shop/Shop/Areas/Admin/Controllers/ProductAttributeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Shop.Models;

namespace Shop.Areas.Admin.Controllers
{
    [Authorize]
    public class ProductAttributeController : Controller
    {
        //
        // GET: /Admin/ProductAttribute/

        public ActionResult Index()
        {
            using (var context = new ShopContainer())
            {
                var productAttributes = context.ProductAttribute.Include("ProductAttributeValues").ToList();
                return View(productAttributes);
            }
        }

        public ActionResult Create()
        {
            return View(new ProductAttribute());
        }

        [HttpPost]
        public ActionResult Create(ProductAttribute model)
        {
            try
            {
                using (var context = new ShopContainer())
                {
                    if (string.IsNullOrEmpty(model.ValueType))
                        model.ValueType = string.Empty;
                    context.AddToProductAttribute(model);
                    context.SaveChanges();
                }

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Edit(int id)
        {
            using (var context = new ShopContainer())
            {
                var productAttribute = context.ProductAttribute.First(pa => pa.Id == id);
                return View(productAttribute);
            }
        }

        [HttpPost]
        public ActionResult Edit(int id, FormCollection form)
        {
            using (var context = new ShopContainer())
            {
                var productAttribute = context.ProductAttribute.First(pa => pa.Id == id);
                try
                {
                    TryUpdateModel(productAttribute, new[] { "Name", "SortOrder", "ShowInCommonView" ,"Static"});
                    productAttribute.ValueType = string.IsNullOrEmpty(productAttribute.ValueType) ? string.Empty : form["ValueType"];
                    context.SaveChanges();
                    return RedirectToAction("Index");
                }
                catch
                {

                }
                return View(productAttribute);
            }

        }

      

        public ActionResult Delete(int id)
        {
            using (var context = new ShopContainer())
            {
                try
                {
                    var attribute = context.ProductAttribute.Include("ProductAttributeValues").First(a => a.Id == id);
                    while (attribute.ProductAttributeValues.Any())
                    {
                        var pav = attribute.ProductAttributeValues.First();
                        pav.Products.Clear();
                        context.DeleteObject(pav);
                    }
                    attribute.Categories.Clear();
                    context.DeleteObject(attribute);
                    context.SaveChanges();
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    ViewBag.ErrorMessage = ex.Message +"<br/>"+ ex.InnerException.Message;
                    var productAttributes = context.ProductAttribute.Include("ProductAttributeValues").ToList();
                    return View("Index", productAttributes);
                }
            }
        }


        public ActionResult ProductAttributeValues(int id)
        {
            using (var context = new ShopContainer())
            {

                var productAttribute = context.ProductAttribute.Include("ProductAttributeValues").First(pa => pa.Id == id);
                return View(productAttribute);
            }
        }

        public ActionResult DeleteProductAttributeValue(int id, int productAttributeId)
        {
            using (var context = new ShopContainer())
            {
                var productAttributeValue = context.ProductAttributeValues.First(pav => pav.Id == id);
                productAttributeValue.Products.Clear();
                context.DeleteObject(productAttributeValue);
                context.SaveChanges();
                return RedirectToAction("ProductAttributeValues", new { id = productAttributeId });
            }
        }

        public ActionResult AddProductAttributeValue(int id)
        {
            using (var context = new ShopContainer())
            {
                var productAttribute = context.ProductAttribute.First(pa => pa.Id == id);
                return View(productAttribute);
            }
        }

        [HttpPost]
        public ActionResult AddProductAttributeValue(int id, string attributeValue)
        {
            using (var context = new ShopContainer())
            {
                var productAttribute = context.ProductAttribute.First(pa => pa.Id == id);
                productAttribute.ProductAttributeValues.Add(new ProductAttributeValues { Value = attributeValue });
                context.SaveChanges();
                return RedirectToAction("ProductAttributeValues", new { id = id });
            }
        }
    }
}

Shop/Shop/Areas/Admin/Views/ProductAttribute/AddProductAttributeValue.cshtml
@model Shop.Models.ProductAttribute

@{
    ViewBag.Title = "AddProductAttributeValue";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Добавление значения атрибута "@Model.Name"</h2>

@using(Html.BeginForm())
{
    @Html.HiddenFor(model=>model.Id)
    @Html.TextBox("attributeValue")
    @Html.Raw("&nbsp")
    @Model.ValueType

        <p>
            <input type="submit" value="Сохранить" />
        </p>
    
}

<div>
    @Html.ActionLink("Назад к списку значений", "ProductAttributeValues", "ProductAttribute", new { id =Model.Id},null)
</div>

@section Includes
{
<script type="text/javascript">

    $(function () {
        $("#attributeValue").focus();
    })
</script>
}

Shop/Shop/Areas/Admin/Views/ProductAttribute/Create.cshtml
@model Shop.Models.ProductAttribute

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Создание атрибута</h2>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>Атрибуты</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.ValueType)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.ValueType)
            @Html.ValidationMessageFor(model => model.ValueType)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.ShowInCommonView)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.ShowInCommonView)
            @Html.ValidationMessageFor(model => model.ShowInCommonView)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Static)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Static)
            @Html.ValidationMessageFor(model => model.Static)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.SortOrder)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.SortOrder)
            @Html.ValidationMessageFor(model => model.SortOrder)
        </div>

        <p>
            <input type="submit" value="Сохранить" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Назад к списку атрибутов", "Index")
</div>

Shop/Shop/Areas/Admin/Views/ProductAttribute/Edit.cshtml
@model Shop.Models.ProductAttribute
@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}
<h2>
    Edit</h2>
<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>ProductAttribute</legend>
        @Html.HiddenFor(model => model.Id)
        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.ValueType)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.ValueType)
            @Html.ValidationMessageFor(model => model.ValueType)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.ShowInCommonView)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.ShowInCommonView)
            @Html.ValidationMessageFor(model => model.ShowInCommonView)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.Static)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Static)
            @Html.ValidationMessageFor(model => model.Static)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.SortOrder)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.SortOrder)
            @Html.ValidationMessageFor(model => model.SortOrder)
        </div>
        <p>
            <input type="submit" value="Сохранить" />
        </p>
    </fieldset>
}
<div>
    @Html.ActionLink("Назад к списку атрибутов", "Index")
</div>

Shop/Shop/Areas/Admin/Views/ProductAttribute/Index.cshtml
@model IEnumerable<Shop.Models.ProductAttribute>
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}
@{
    
    if (ViewBag.ErrorMessage != null)
    {
    <div class="errorMessage">
        @Html.Raw(ViewBag.ErrorMessage)
    </div>
    }
}
<h2>
    Атрибуты</h2>
<p>
    @Html.ActionLink("Добавить новую запись", "Create")
</p>
<table>
    <tr>
        <th>
            Название
        </th>
        <th>
            Значения
        </th>
        <th>
            Тип значения
        </th>
        <th>
            Отображать в кратком описании
        </th>
        <th>
            Статический
        </th>
        <th>
            Порядок отображения
        </th>
        <th>
        </th>
    </tr>
    @foreach (var item in Model.OrderBy(a => a.SortOrder))
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @foreach (var value in item.ProductAttributeValues)
                {
                    @Html.Raw(value.Value + "; ")
                }
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ValueType)
            </td>
            <td>
                @Html.Raw(item.ShowInCommonView ? "да" : "нет")
            </td>
            <td>
                @Html.Raw(item.Static ? "да" : "нет")
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SortOrder)
            </td>
            <td style="white-space: nowrap">
                @Html.ActionLink("Редактировать", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Удалить", "Delete", new { id = item.Id }, new { onclick = "return confirm('Удалить атрибут? При удалении атрибута будут также удалены все значения данного атрибута в т.ч. и в продуктах!')" })
                @if (!item.Static)
                {
                    @Html.Raw("|")
                    @Html.ActionLink("Значения", "ProductAttributeValues", new {id = item.Id})
                }
            </td>
        </tr>
    }
</table>

Shop/Shop/Areas/Admin/Views/ProductAttribute/ProductAttributeValues.cshtml
@model Shop.Models.ProductAttribute

@{
    ViewBag.Title = "ProductAttributeValues";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Значения атрибута @Model.Name</h2>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>


@Html.ActionLink("Добавить значение", "AddProductAttributeValue","ProductAttribute",new{id=Model.Id},null)
<br/>
<br/>
<table>
@foreach (var item in Model.ProductAttributeValues)
{
    <tr>
        <td>@item.Value</td>
        <td>@Model.ValueType</td>
        <td>@Html.ActionLink("[удалить]", "DeleteProductAttributeValue", "ProductAttribute", new { id = item.Id, productAttributeId =item.PruductAttributeId},null)</td>
    </tr>
}
</table>
<br/>

<div>
    @Html.ActionLink("Назад к спику атрибутов", "Index")
</div>