Posh/Posh/Areas/Admin/Controllers/AlbumController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Posh.Helpers;
using Posh.Models;

namespace Posh.Areas.Admin.Controllers
{
    public class AlbumController : Controller
    {
        //
        // GET: /Admin/Album/

        public ActionResult Create()
        {
            return View(new Album());
        }

        [HttpPost]
        public ActionResult Create(FormCollection form, HttpPostedFileBase uploadFile)
        {
            using (var context = new ModelContainer())
            {
                var album = new Album{ImageSource = ""};
                TryUpdateModel(album,
                               new[]
                                   {
                                       "Name",
                                       "Title",
                                       "SortOrder"
                                   });


                string fileName = IOHelper.GetUniqueFileName("~/Content/Images", uploadFile.FileName);
                string filePath = Server.MapPath("~/Content/Images");
                filePath = Path.Combine(filePath, fileName);
                uploadFile.SaveAs(filePath);

                album.ImageSource = fileName;


                context.AddToAlbum(album);
                context.SaveChanges();
                return RedirectToAction("Index", "Home", new { Area = "", id = "catalogue" });
            }
        }

        public ActionResult Edit(int id)
        {
            using (var context = new ModelContainer())
            {
                var album = context.Album.First(p => p.Id == id);
                return View(album);
            }
        }
        [HttpPost]
        public ActionResult Edit(int id, FormCollection form)
        {
            using (var context = new ModelContainer())
            {
                var album = context.Album.First(p => p.Id == id);
                TryUpdateModel(album,
                               new[]
                                   {
                                       "Name",
                                       "Title",
                                       "SortOrder"
                                   });
                context.SaveChanges();
            }
            return RedirectToAction("Index", "Home", new { Area = "", id = "catalogue" });
        }

        public ActionResult Delete(int id)
        {
            using (var context = new ModelContainer())
            {
                var album = context.Album.Include("Products").First(a => a.Id == id);
                if (!album.Products.Any())
                {
                    context.DeleteObject(album);
                    context.SaveChanges();
                }
            }
            return RedirectToAction("Index", "Home", new { Area = "", id = "catalogue" });
        }
    }
}

Posh/Posh/Controllers/AlbumsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Posh.Helpers;
using Posh.Models;

namespace Posh.Controllers
{
    public class AlbumsController : Controller
    {
        //
        // GET: /Albums/

        public ActionResult Index(string id)
        {
            using (var context = new ModelContainer())
            {
                var model = new CatalogueModel(context, "catalogue",id);
                this.SetSeoContent(model);

                ViewBag.MainMenu = model.MainMenu;
                ViewBag.isHomePage = model.IsHomePage;

                ViewBag.Categories = model.Categories;
                ViewBag.Elements = model.Elements;


                model.Albums = ApplyFilter(model);


                if (model.Album != null)
                    return View("Details",model);

                return View(model);
            }
        }

        public List<Album> ApplyFilter(CatalogueModel model)
        {
           


            if (WebSession.Categories.Count > 0)
            {
                foreach (var album in model.Albums)
                {
                    foreach (var product in album.Products)
                    {
                        if (product.Categories.Intersect(WebSession.Categories).Count() == 0)
                        {
                            product.Hidden = true;
                        }
                    }
                }
            }

            if (WebSession.Elements.Count > 0)
            {
                foreach (var album in model.Albums)
                {
                    foreach (var product in album.Products)
                    {
                        if (product.Elements.Intersect(WebSession.Elements).Count() == 0)
                        {
                            product.Hidden = true;
                        }
                    }
                }
            }


            var resultAlbums = new List<Album>();

            foreach (var album in model.Albums)
            {
                if(Request.IsAuthenticated)
                    resultAlbums.Add(album);
                else
                if (album.Products.Where(p => !p.Hidden).Count() > 0)
                    resultAlbums.Add(album);
            }

            return resultAlbums;

        }

        [HttpPost]
        public ActionResult Index(FormCollection form)
        {
            using (var context = new ModelContainer())
            {
                var model = new CatalogueModel(context, "catalogue", null);
                this.SetSeoContent(model);

                ViewBag.MainMenu = model.MainMenu;
                ViewBag.isHomePage = model.IsHomePage;


                WebSession.Categories.Clear();
                WebSession.Elements.Clear();

                List<Category> checkedCategories = (from category in model.Categories where form["hcat_" + category.Id] == "1" select category).ToList();
                List<Element> checkedElements = (from element in model.Elements where form["el_" + element.Id] == "true,false" select element).ToList();

                WebSession.Categories.AddRange(checkedCategories);
                WebSession.Elements.AddRange(checkedElements);


                model.Albums = ApplyFilter(model);

                

               


                //return RedirectToAction("Index");
                return View(model);
            }
        }
    }
}

Posh/Posh/Views/Albums/Details.cshtml
@using Posh.Helpers
@model Posh.Models.CatalogueModel
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section Includes
{
    <link href="@Url.Content("~/Content/Catalogue.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/fancybox/jquery.fancybox-1.3.4.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Content/fancybox/jquery.fancybox-1.3.4.js")" type="text/javascript"></script>
    <script type="text/javascript">
        $(function () {
            $(".fancy").fancybox({ titlePosition: 'inside', showCloseButton: true, cyclic: false, showNavArrows: true, padding: 0, margin: 0, centerOnScroll: true });
        });
    </script>
}
@section Title
{
    <div class="catalogue">
        <div class="title">
            @Html.ActionLink(Model.Content.Title, "Index", "Albums", new { id = "" }, null)
        </div>
        <div class="filter">
            @Html.Partial("_Filter")
        </div>
        <div class="clear">
        </div>
    </div>
}
@section SeoTitle
{
    @if (!string.IsNullOrEmpty(Model.Content.SeoTitle))
    {
        <div class="title seo">
            @Model.Content.SeoTitle
        </div>
    }
}
@section SeoContent
{
    @if (!string.IsNullOrEmpty(Model.Content.SeoText))
    {
        <div class="content seo">
            @Html.Raw(Model.Content.SeoText)
        </div>
    }
}
@section Content
{
    @if (!string.IsNullOrEmpty(Model.Content.Text))
    {
        <div class="content">
            @Html.Raw(Model.Content.Text)
        </div>
    }
}
@{
    <div id="productsContainer">
        <div id="productsAlbumTitle">
            &raquo; @Model.Album.Title
        </div>
        @if (Request.IsAuthenticated)
        {
            @Html.ActionLink("Новый элемент", "Create", "Product", new {Area = "Admin", id = Model.Album.Id}, new {@class = "adminLink"})
            <br /><br />
        }
        <div id="products">
            @foreach (var image in Model.Album.Products.Where(p=>!p.Hidden))
            {
                <div class="productItem">
                @if (Request.IsAuthenticated)
                 {
                     <div class="adminLinksContainer">
                         @Html.ActionLink("Редактировать", "Edit", "Product", new {Area = "Admin", id = image.Id}, new {@class = "adminLink"})<br/>
                         @Html.ActionLink("Удалить", "Delete", "Product", new { Area = "Admin", id = image.Id }, new { @class = "adminLink", onclick = "return confirm('Удалить изображение?')" })<br/>
                         @Html.ActionLink("Сделать обложкой альбома", "SetDefault", "Product", new {Area = "Admin", id = image.Id}, new {@class = "adminLink", onclick = "return confirm('Сделать обложкой альбома?')"})
                     </div>
                 }
                    <a rel="@Html.Raw("group" + Model.Album.Id)" href="../../../Content/Images/@image.ImageSource" title="@image.Title" class="fancy">
                    @Html.Raw(Html.CachedImage("~/Content/Images/", image.ImageSource, "thumbnail0", ScaleMode.Corp))
                    </a>
                </div>
            }
            <div id="lastProductItem" class="productItem">
                &raquo; @Html.ActionLink("В меню", "Index", "Albums", new { id = "" }, null)
            </div>
            <div class="clear">
        </div>
        </div>
    </div>
   
}

Posh/Posh/Views/Albums/Index.cshtml
@using Posh.Helpers
@model Posh.Models.CatalogueModel
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section Includes
{
    <link href="@Url.Content("~/Content/Catalogue.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/fancybox/jquery.fancybox-1.3.4.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Content/fancybox/jquery.fancybox-1.3.4.js")" type="text/javascript"></script>
    <link href="@Url.Content("~/Content/SearchSelector.css")" rel="stylesheet" type="text/css" />
    <script type="text/javascript">
        $(function () {
            $(".fancy").fancybox({ hideOnContentClick: false, showCloseButton: true, showNavArrows: false });
        });
</script>
}
@section Title
{
    <div class="catalogue">
        <div class="title">
            @Model.Content.Title
        </div>
        <div class="filter">
           @Html.Partial("_Filter")
        </div>
        <div class="clear">
        </div>
    </div>
}
@section SeoTitle
{
    @if (!string.IsNullOrEmpty(Model.Content.SeoTitle))
    {
        <div class="title seo">
            @Model.Content.SeoTitle
        </div>
    }
}
@section SeoContent
{
    @if (!string.IsNullOrEmpty(Model.Content.SeoText))
    {
        <div class="content seo">
            @Html.Raw(Model.Content.SeoText)
        </div>
    }
}
@section Content
{
    @if (!string.IsNullOrEmpty(Model.Content.Text))
    {
        <div class="content">
            @Html.Raw(Model.Content.Text)
        </div>
    }
}
@{
    <div id="catalogueContainer">
    @if (Request.IsAuthenticated)
    {
        @Html.ActionLink("Новый альбом", "Create", "Album", new {Area = "Admin"}, new {@class = "adminLink"})
        <div class="clear">
        </div>
    }
        @foreach (var album in Model.Albums)
        {
            @Html.Partial("_Album", album)
        }
        <div class="clear">
        </div>
    </div>
}

Posh/Posh/Views/Albums/_Album.cshtml
@using Posh.Helpers
@model Posh.Models.Album
<div class="album">
@if(Request.IsAuthenticated)
{
    <div class="abs">
        @Html.ActionLink("Редактировать альбом", "Edit", "Album", new { Area = "Admin", id = Model.Id }, new { @class = "adminLink" })<br/>
        @Html.ActionLink("Удалить альбом", "Delete", "Album", new { Area = "Admin", id = Model.Id }, new { @class = "adminLink", onclick = "return confirm('Удалить альбом? (удаляются только пустые альбомы)')" })<br/>
    </div>
}

    <div class="album-title">
        @Html.ActionLink(Model.Title, "Index", "Albums", new { id = Model.Name }, null)
    </div>
    @Html.Raw(Html.ActionLink("[IMAGE]", "Index", "Albums", new { id = Model.Name }, null).ToString().Replace("[IMAGE]", Html.CachedImage("~/Content/Images/", Model.ImageSource, "thumbnail1", ScaleMode.Corp)))
</div>

Posh/Posh/Views/Albums/_Filter.cshtml
@using Posh.Helpers
 <table class="filterTable">
                <tr>
                    <th>
                        Показать категории:
                    </th>
                    <td>
                        
                        @if (WebSession.Categories.Count>0)
                        {
                            foreach (var category in WebSession.Categories)
                            {
                                <div class="filterItem">@category.Title</div>
                            }
                        }else
                        {
                            <div class="showAll">(показываются все)</div>
                        }
                        
                    </td>
                    <td rowspan="2">
                        @Html.ActionLink("Изменить", "ShowFilter", "Home", new { Area = "", id = "" }, new{@class="changeFilter fancy"})
                    </td>
                </tr>
                <tr>
                    <th>
                        Показать элементы:
                    </th>
                    <td>
                        @if (WebSession.Elements.Count>0)
                        {
                            foreach (var element in WebSession.Elements)
                            {
                                <div class="filterItem">@element.Title</div>
                            }
                        }else
                        { <div class="showAll">(показываются все)</div>
                        }
                    </td>
                </tr>
            </table>